"""empty message

Revision ID: 41e9fc7bb5a9
Revises: 
Create Date: 2023-04-04 08:50:12.901845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41e9fc7bb5a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_creators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('Image', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Image', sa.String(length=255), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('heading', sa.String(length=255), nullable=True),
    sa.Column('highlight', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('blog_creator', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blog_creator'], ['blog_creators.id'], ),
    sa.ForeignKeyConstraint(['category'], ['blog_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('blog_post', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blog_post'], ['blog_post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_heading',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('heading', sa.Text(), nullable=True),
    sa.Column('parent_blog', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_blog'], ['blog_post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_paragraph',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('parent_blog_heading', sa.Integer(), nullable=True),
    sa.Column('parent_blog', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_blog'], ['blog_post.id'], ),
    sa.ForeignKeyConstraint(['parent_blog_heading'], ['blog_heading.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_paragraph')
    op.drop_table('blog_heading')
    op.drop_table('blog_comment')
    op.drop_table('blog_post')
    op.drop_table('blog_creators')
    op.drop_table('blog_categories')
    # ### end Alembic commands ###
